// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/ports/oauth_validator.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/ports/oauth_validator.go -destination=internal/mocks/mock_oauth_validator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/yuki5155/go-google-auth/internal/application/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthValidator is a mock of OAuthValidator interface.
type MockOAuthValidator struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthValidatorMockRecorder
	isgomock struct{}
}

// MockOAuthValidatorMockRecorder is the mock recorder for MockOAuthValidator.
type MockOAuthValidatorMockRecorder struct {
	mock *MockOAuthValidator
}

// NewMockOAuthValidator creates a new mock instance.
func NewMockOAuthValidator(ctrl *gomock.Controller) *MockOAuthValidator {
	mock := &MockOAuthValidator{ctrl: ctrl}
	mock.recorder = &MockOAuthValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthValidator) EXPECT() *MockOAuthValidatorMockRecorder {
	return m.recorder
}

// ValidateToken mocks base method.
func (m *MockOAuthValidator) ValidateToken(ctx context.Context, idToken, audience string) (*ports.OAuthUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, idToken, audience)
	ret0, _ := ret[0].(*ports.OAuthUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockOAuthValidatorMockRecorder) ValidateToken(ctx, idToken, audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockOAuthValidator)(nil).ValidateToken), ctx, idToken, audience)
}
