// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/ports/token_generator.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/ports/token_generator.go -destination=internal/mocks/mock_token_generator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ports "github.com/yuki5155/go-google-auth/internal/application/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenGenerator is a mock of TokenGenerator interface.
type MockTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockTokenGeneratorMockRecorder is the mock recorder for MockTokenGenerator.
type MockTokenGeneratorMockRecorder struct {
	mock *MockTokenGenerator
}

// NewMockTokenGenerator creates a new mock instance.
func NewMockTokenGenerator(ctrl *gomock.Controller) *MockTokenGenerator {
	mock := &MockTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenGenerator) EXPECT() *MockTokenGeneratorMockRecorder {
	return m.recorder
}

// GenerateTokenPair mocks base method.
func (m *MockTokenGenerator) GenerateTokenPair(userInfo ports.UserInfo) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPair", userInfo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockTokenGeneratorMockRecorder) GenerateTokenPair(userInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockTokenGenerator)(nil).GenerateTokenPair), userInfo)
}

// GetAccessTokenExpiry mocks base method.
func (m *MockTokenGenerator) GetAccessTokenExpiry() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenExpiry")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetAccessTokenExpiry indicates an expected call of GetAccessTokenExpiry.
func (mr *MockTokenGeneratorMockRecorder) GetAccessTokenExpiry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenExpiry", reflect.TypeOf((*MockTokenGenerator)(nil).GetAccessTokenExpiry))
}

// GetRefreshTokenExpiry mocks base method.
func (m *MockTokenGenerator) GetRefreshTokenExpiry() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenExpiry")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRefreshTokenExpiry indicates an expected call of GetRefreshTokenExpiry.
func (mr *MockTokenGeneratorMockRecorder) GetRefreshTokenExpiry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenExpiry", reflect.TypeOf((*MockTokenGenerator)(nil).GetRefreshTokenExpiry))
}

// RefreshAccessToken mocks base method.
func (m *MockTokenGenerator) RefreshAccessToken(refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAccessToken", refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshAccessToken indicates an expected call of RefreshAccessToken.
func (mr *MockTokenGeneratorMockRecorder) RefreshAccessToken(refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAccessToken", reflect.TypeOf((*MockTokenGenerator)(nil).RefreshAccessToken), refreshToken)
}

// ValidateAccessToken mocks base method.
func (m *MockTokenGenerator) ValidateAccessToken(accessToken string) (*ports.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", accessToken)
	ret0, _ := ret[0].(*ports.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenGeneratorMockRecorder) ValidateAccessToken(accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenGenerator)(nil).ValidateAccessToken), accessToken)
}
